# monitoring scripts & service deployments for data providers provisionning
-   name: deploy the data ingestion monitoring script
    template:
        src: data_ingestion_monitoring_v2.sh.j2
        dest: /home/{{ data_provider }}/admin/data_ingestion_monitoring_v2.sh
        owner: "{{ data_provider }}"
        group: "{{ data_provider }}"
        mode:   "u=rwx,g=r,o=r"
-   name: deploy the file rotation script
    template:
        src: data_ingestion_file_rotation_v2.sh.j2
        dest: /home/{{ data_provider }}/admin/data_ingestion_file_rotation_v2.sh
        owner: "{{ data_provider }}"
        group: "{{ data_provider }}"
        mode:   "u=rwx,g=r,o=r"
-   name: deploy the file rotation service
    template:
        src: data.ingestion.file.rotation.j2
        dest: /etc/systemd/system/data.ingestion.file.rotation.{{ data_provider }}.{{ depenvironment }}.service
        owner: root
        group: root
-   name: deploy the data ingestion monitoring service
    template:
        src: monitoring.ingester.data.j2
        dest: /etc/systemd/system/monitoring.ingester.data.{{ data_provider }}.{{ depenvironment }}.service
        owner: root
        group: root
