---
# file: playbooks/filebeat/enable_service.yml

- hosts: tpgbam_servers
  tasks:
    - name: Enable Filebeat service
      systemd:
        name: filebeat.{{ data_provider }}.{{ env }}
        daemon_reload: true
        enabled: true
        state: started
