filebeat.prospectors:
- input_type: log
  paths:
    - /Users/macphil1/Downloads/filebeat-6.2.4-darwin-x86_64/sms/*.csv
    
  # Ignore the first line with column headings
  exclude_lines: ["^date,phone,theme,cost,currency,delivery_status"]



#================================ Outputs =====================================

output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["esc7.antaes.ch:9200"]
  pipeline: "tpgmobilebuy"
  template.name: "filebeat"
  template.path: "filebeat.template.json"
  template.overwrite: false
  "username": "tpg_ingest"
  "password": "tpg_ingest"

#output.console:
#  pretty: true