---
# file: playbooks/monitoring/deploy_script.yml

- hosts: tpgbam_servers
  tasks:
    - name: Deploy data ingestion monitoring script
      template:
        src: "../../templates/monitoring/data_ingestion_monitoring_v2.sh.j2"
        dest: "/home/{{ data_provider }}/admin/data_ingestion_monitoring_v2.sh"
        owner: "{{ data_provider }}"
        group: "{{ data_provider }}"
        mode:   "u=rwx,g=r,o=r"

    - name: Deploy the file rotation script
      template:
        src: "../../templates/monitoring/data_ingestion_file_rotation_v2.sh.j2"
        dest: "/home/{{ data_provider }}/admin/data_ingestion_file_rotation_v2.sh"
        owner: "{{ data_provider }}"
        group: "{{ data_provider }}"
        mode:   "u=rwx,g=r,o=r"
