# deploy the filebeat service
-   name: deploy the filebeat configuration
    template:
        src: filebeat.j2
        dest: /etc/filebeat/filebeat.{{ data_provider }}.{{ depenvironment }}.yml
        owner: root
        group: root
-   name: deploy the filebeat service
    template:
        src: filebeat.service.j2
        dest: /etc/systemd/system/filebeat.{{ data_provider }}.{{ depenvironment }}.service
        owner: root
        group: root